language: php
php:
  - "7.3"
  - "7.4snapshot"

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.4snapshot

services:
  - redis-server

before_install:
  - echo "apc.enabled = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "apc.enable_cli = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension = apcu.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - phpenv rehash

install:
  - travis_retry composer update --prefer-dist

jobs:
  include:
    - stage: "Code Quality"
      name: PHPCS
      install: travis_retry composer install --prefer-dist
      php: "7.3"
      script:
        - ./vendor/bin/phpcs
    - stage: "Code Quality"
      name: Psalm
      install: travis_retry composer install --prefer-dist
      php: "7.3"
      script:
        - ./vendor/bin/psalm --shepherd
    - stage: test
      name: Integration
      services:
        - docker
      install: travis_retry composer install --prefer-dist
      before_script:
        - docker-compose up -d
        - sleep 15
        - docker ps -a
      script:
        - docker-compose exec phpunit env ADAPTER=apcu vendor/bin/phpunit --testsuite=functionnal
        - docker-compose exec phpunit env ADAPTER=redis vendor/bin/phpunit --testsuite=functionnal
    - stage: test
      name: Mutation testing
      services:
        - redis-server
      install: travis_retry composer install --prefer-dist
      php: "7.3"
      script:
        - ./vendor/bin/infection --min-msi=90 --min-covered-msi=90

script:
  - vendor/bin/phpunit --verbose --colors --coverage-clover=coverage.xml

after_success:
- bash <(curl -s https://codecov.io/bash)

stages:
  - "Code Quality"
  - test

cache:
  directories:
    - vendor
    - $HOME/.composer/cache
