version: "2"

services:
  nginx:
    build:
      context: nginx/
    depends_on:
      - php-fpm
  php-fpm:
    build:
      context: php-fpm/
      args:
        PHP_VERSION: ${PHP_VERSION:-8.1}
    volumes:
      - .:/var/www/html
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
      - pushgateway
  redis:
    image: redis
  pushgateway:
    image: prom/pushgateway
  phpunit:
    build:
      context: php-fpm/
      args:
        PHP_VERSION: ${PHP_VERSION:-8.1}
    volumes:
      - .:/var/www/html
    environment:
      - REDIS_HOST=redis
    depends_on:
      - nginx
      - pushgateway
      - redis
